version: '3.8'

services:
  app:
    container_name: nestjs_app
    build: .
    ports:
      - "444:444"
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: 'YourStrong!Passw0rd'
      DB_DATABASE: SIMTEFAC
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: