export enum eError {
    USER_ALREADY_EXISTS = 0,
    USER_ALREADY_REGISTERED = 1,
    USER_NOT_FOUND = 2,
    NOT_ENOUGTH_PARAMETERS = 3,
    INVALID_PARAMETERS = 4,
    RESOURCE_NOT_FOUND = 5,
    WRONG_PASSWORD = 6,
    USER_ALREADY_SUBSCRIBED = 7,
    SUBSCRIPTION_NOT_FOUND = 8,
    EVENT_NOT_FOUND = 9,
    EVENT_IS_FULL = 10,
    INVALID_TOKEN = 11,
    RECORD_ALREADY_CREATED = 12
}